application: saasbook
version: 1
runtime: python
api_version: 1

handlers:

- url: /files/?.*
  script: bookware.py

- url: /?
  script: bookware.py

- url: /admin/.*
  script: bookware.py
  login: admin

- url: /main.css
  static_files: main.css
  upload: main.css
